### ISSUE TITLE
Different bubblesheet

### ISSUE THREAD

**Issue by kalyan1** [rbaron/omr#2]
It is simple and  good code.
If we want to create different type of bubblesheets, What changes need to done in the code. Can you add documents or some tutorial for the same.

**Comment by rbaron** [comment]
Hi @kalyan1,

On a high level, the program looks for "corners" in the input image, of which there are four. Once this corners are found, the program applies a transformation so that these corners form a 512x512 square image.
The next step is scanning this 512x512 square image and extracting images of each question from it. This is done by the function `get_question_patch(transf, q_number)`. The arguments are the 512x512 square image (`transf`) and the number of the question to "extract". This function assumes that questions are evenly-spaced with fixed dimensions (for instance, the "height" of each question is 80).
If you were to use a different sheet, this is one point you'd have to modify the script.

Once a question patch (a rectangular image patch containing a single question) is extracted, there's a second step which consisits of a _horizontal_ scan inside this patch so we can identify which alternative was marked. This is done by the function `get_alternative_patches` and assumes that the alternatives are spaced by a fixed dimension. This is the second place you'd have to modify the script.

I hope that answers the question! Feel free to comment if you have any questions :+1:

**Comment by kalyan1** [comment]
Thanks a lot. It helps.
Kalyan
