### ISSUE TITLE
Hi rbaron different sheet

### ISSUE THREAD

**Issue by iderbukh** [rbaron/omr#4]
Hello dear Baron. I want to use a different sheet, but i can't do this. I changed fixed dimension (height of each question is 40) because i used 20 questions. What changes need to done in the code?

**Comment by rbaron** [comment]
@iderbukh you'll probably have to change a few more places. Keep in mind that is more of a "proof of concept". The program works by:

1. Finding the corners in the image (so your new sheet would have to have the corners drawn on them);
2. Transforming the input image so that the detected corners are the actual image corners;
3. Scanning the transformed image at _fixed_ "vertical" steps so we can analyze every question. You would have to change these fixed steps to match your new sheet ( this is the function that handles this: https://github.com/rbaron/omr/blob/master/omr.py#L124);
4 For each question to be analyzed, we scan it "horizontally" using fixed steps as well (here: https://github.com/rbaron/omr/blob/master/omr.py#L142). You'd also have to change these widths to match your new sheet;

Let me know if I can help you any further :)

**Comment by iderbukh** [comment]
Hello dear Baron, I don't know how to change sheet_coord_to_trans_coord. It has started to scan 3rd question and has not match questions. i changed coloured value on the sheet_coord_to_trans_coord. is it right? :P
![ywuulah](https://cloud.githubusercontent.com/assets/23094565/26021762/6b5c65d8-37cf-11e7-999c-287de16bbb3d.png)
This is new sheet
[](url)[
![sheet](https://cloud.githubusercontent.com/assets/23094565/26021216/40ce8e50-37c4-11e7-9c76-d5b8ec349d89.png)
](url)

**Comment by rbaron** [comment]
Hi @iderbukh. These coordinates are kinda tricky to get right. This is mostly because we have 2 coordinate systems:

1. Original "sheet" coordinates. This is arbitrary, but I took it to be 744.055 width by 1052.362 height, since it was easier for me to measure with the sheet I had. Now I see it might be a good idea to refactor this 😬.

2. Transformed coordinates. Once we find the sheet in the original image, it is converted to a 512 x 512 square image.

All coordinates are related to the system 1. There is the utility function `sheet_coord_to_transf_coord` that transforms the coordinates for us.

Once that's clear, there might be a few ways to approach the problem of having more questions on a sheet:

Approach 1. Make the original sheet "bigger" (that is, changing the aspect ratio), like you did. This would mean we would have to:

1.1 Adjust the `sheet_coord_to_transf_coord` function (because the original size of 744x1052 is no longer valid, and so the transformations will be wrong);
1.2 Adjust the `get_question_patch` like you already did.

Approach 2. Keep the original sheet size untouched, and just cramming more questions into the same space. It seems that by doing that, you would simply have to change the `get_question_patch` function, because the coordinate transformations will still work.

It seems like approach 2 is simpler, so I would recommend trying that. 

Does this help? Let me know how it goes!

**Comment by iderbukh** [comment]
Hello dear rbaron, i did everything. but it doesn't work. What should i do now?

**Comment by rbaron** [comment]
Hi @iderbukh. Let me know if you have specific questions on how to approach this. As I suggested, I think the second approach I mentioned on my comment is a good choice.
